In [1]:

from fiducials import *
import numpy as np
import glob
from distort_calibration import *
from cartesian import*
from registration_3d import*
from optical_tracking import*
from eval import *
from pathlib import Path
import argparse
from distort_calibration import *
from distortion_correction import *
from em_tracking import *
from improved_em_tracking import *
data_dir = 'DATA/'
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
runtype = ['debug','debug','debug','debug','debug','debug', 'unknown', 'unknown', 'unknown', 'unknown']
pa = "pa2-"



In [2]:
for num in range(10):
    
    data_type = num
    letter = num
    print(data_dir + pa + runtype[data_type] + '-' + letters[letter])
##################################################################################################### redundant code, need to change if we have time
    output_path = glob.glob(data_dir + pa + runtype[data_type] + '-' + letters[letter] + '-output1.txt')
    output_data = []
    read_file = open(output_path[0], mode='r')
    lines = read_file.read().splitlines()
    for num in range(len(lines)):
        output_data.append( lines[num].split(',') )
        for i in range(len(output_data[-1])):
            output_data[-1][i] = output_data[-1][i].strip()
    Nc = int(output_data[0][0])
    Nframes = int(output_data[0][1])
    output_name = output_data[0][2]
    C_expected = np.asarray(output_data[3:]).astype(float)
    # print(output_data.shape)
    
####################
# get distortion correction matrix from previous code?
####################
    C_exp, Nc, Nframes,C = distort_calibration( data_dir ,pa, runtype[data_type]  , letters[letter]  , output = 0 )    
    X, qmin, qmax = distortion_correction(C, C_expected, order=5)
    empivot = improved_em_tracking(data_dir, pa, runtype[data_type] , letters[letter], output=0)
##################################################################################################### end of redundant code
    F_reg = em_ct(data_dir,"pa2-",runtype[data_type], letters[letter],X, qmin, qmax,empivot)

    em_nav2ct( data_dir,"pa2-",runtype[data_type], letters[letter] , F_reg , X, qmin, qmax,empivot)[0]


DATA/pa2-debug-a
output2:
 [[148.33045102 118.9743815   43.20128926]
 [ 76.2643682  116.05482984 152.64105749]
 [ 36.90681751 148.36883105 170.97400522]
 [ 75.80310504  75.61865711 172.00544659]]
DATA/pa2-debug-b
output2:
 [[ 89.08374268  84.03840511 170.5168616 ]
 [ 39.6642811  163.39777591 157.31854953]
 [117.8704042  156.23204503  81.73887778]
 [ 35.32053638  36.3246116  134.20247988]]
DATA/pa2-debug-c
output2:
 [[ 91.53800955  88.10055798 161.1239647 ]
 [ 46.08932952 130.6777352   99.30815198]
 [127.3811878   95.92540333 171.89199928]
 [107.03227105  64.06329707  39.19996381]]
DATA/pa2-debug-d
output2:
 [[125.32893852 148.45393593  50.19897799]
 [105.36770322  79.75533729  97.69662606]
 [162.48328116  32.46620096  47.74399034]
 [ 47.11589998 138.05654316  27.11831618]]
DATA/pa2-debug-e
output2:
 [[162.26000812  75.20451555 117.88939643]
 [ 86.53667703  79.72212448  84.79222912]
 [ 45.40333018 169.66745964  99.58065088]
 [ 66.67843822  45.18495272  74.2233558 ]]
DATA/pa2-debug-f
out