In [1]:
import math
math.factorial(3)
from cartesian import *

import numpy as np
import glob
from distort_calibration import *
from cartesian import*
from registration_3d import*
from optical_tracking import*
from em_tracking import *
from eval import *
from pathlib import Path
import argparse
from distort_calibration import *
from distortion_correction import *

In [2]:
def get_Bern_comp(N, k, v):
    
    n_k = combinations(N, k)
    # print(np.power(v, k).shape)
    Bern_Nkv = (n_k * np.power((1 - v), (N - k))) * np.power(v, k)
    return Bern_Nkv

In [3]:
def get_Bern( points , qmin, qmax, order= 5 ):
    scaled_points = scale( points , qmin, qmax )[0]
    N = order
    scaled_x = scaled_points[:, 0].reshape( ( -1, 1 ) )
    scaled_y = scaled_points[:, 1].reshape( ( -1, 1 ) )
    scaled_z = scaled_points[:, 2].reshape( ( -1, 1 ) )
    # print((get_Bern_comp(N, 0, scaled_x) * 
    #             get_Bern_comp(N, 0, scaled_y) *
    #             get_Bern_comp(N, 0, scaled_z)).shape)
    power = order + 1
    result = np.zeros( ( points.shape[0], ( order + 1 ) ** 3 ) )

    for i in range(power):
        for j in range(power):
            for k in range(power):
                Fijk = (get_Bern_comp(N, i, scaled_x) * 
                get_Bern_comp(N, j, scaled_y) *
                get_Bern_comp(N, k, scaled_z))
                pass
                

In [4]:
combinations(5, 2)

10.0

In [5]:
data_type = 0
letter = 0
data_dir = 'DATA/'
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']
type = ['debug', 'unknown']

output_path = glob.glob(data_dir + 'pa2-' + type[data_type] + '-' + letters[letter] + '-output1.txt')
output_data = []
read_file = open(output_path[0], mode='r')
lines = read_file.read().splitlines()
for num in range(len(lines)):
    output_data.append( lines[num].split(',') )
    for i in range(len(output_data[-1])):
        output_data[-1][i] = output_data[-1][i].strip()
Nc = int(output_data[0][0])
Nframes = int(output_data[0][1])
print(Nc, Nframes)
output_name = output_data[0][2]
output_data = np.asarray(output_data[3:]).astype(float)
print(output_data.shape)

C_exp, Nc, Nframes = distort_calibration( data_dir , type[data_type] , letters[letter]  , output = 0 )

# print(C_exp.shape, Nc, Nframes)
X, qmin, qmax = distortion_correction(C_exp, output_data, order=5)
print(X, qmin, qmax)

27 125
(3375, 3)
AX-B max error:  0.008740115671116655
[[ 85.27497324  85.27609716  85.28648493]
 [ 85.28771584  85.28133332 240.59222333]
 [ 85.2768356   85.30774379 395.98815756]
 [ 85.27405907  85.23207367 551.25971879]
 [ 85.28305694  85.32243905 706.63147116]
 [ 85.27555926  85.27190837 861.97796845]
 [ 85.30387233 240.63950195  85.26305126]
 [ 85.2528675  240.53020338 240.67726022]
 [ 85.25188481 240.64390247 395.92485472]
 [ 85.3606625  240.65121271 551.32681095]
 [ 85.25936022 240.62246562 706.65983665]
 [ 85.28488375 240.60101481 861.91039341]
 [ 85.25373375 395.90360835  85.29894981]
 [ 85.24461559 396.12555087 240.51246113]
 [ 85.4134123  395.82168742 396.08017876]
 [ 85.13927178 396.05902696 551.15965739]
 [ 85.29997026 395.8194467  706.61224523]
 [ 85.28465199 396.00941701 862.05028137]
 [ 85.28926183 551.34513728  85.26987167]
 [ 85.39880133 551.12772648 240.73971505]
 [ 85.09297973 551.4850621  395.77194572]
 [ 85.3901012  551.09201165 551.47568064]
 [ 85.30420316 551.46

In [6]:
get_Bern(C_exp, qmin, qmax)